services:
  - type: web
    name: ai-tutor
    env: python
    plan: free
    pythonVersion: 3.11.9  # Specify Python 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
